# Generated by Django 5.1.3 on 2025-01-12 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='certificacoes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experiencia',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='formacao',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='idiomas',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='links',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nome_completo',
        ),
        migrations.DeleteModel(
            name='Inscricao',
        ),
    ]
