# Generated by Django 5.1.3 on 2025-01-09 19:47

import vagas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tipo_usuario',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(default='Não informado', max_length=14, unique=True, validators=[vagas.models.validar_cpf]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='beneficios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='carga_horaria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
