# Generated by Django 5.1.3 on 2025-01-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='requisitos',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='salario',
        ),
        migrations.AddField(
            model_name='vaga',
            name='localizacao',
            field=models.CharField(default='Não especificado', max_length=100),
        ),
    ]
