# Generated by Django 5.1.3 on 2025-01-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_remove_profile_certificacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='beneficios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='prazo_inscricao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
