# Generated by Django 5.1.3 on 2025-01-03 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_remove_vaga_requisitos_remove_vaga_salario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='vagas.vaga')),
            ],
        ),
    ]
