# Generated by Django 5.1.3 on 2025-01-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_vaga_salario_inscricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaga',
            old_name='salario',
            new_name='faixa_salarial_maxima',
        ),
        migrations.AddField(
            model_name='vaga',
            name='faixa_salarial_minima',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='tipo_de_vaga',
            field=models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'Pessoa Jurídica'), ('Estágio', 'Estágio'), ('Temporário', 'Temporário')], default='CLT', max_length=50),
        ),
    ]
