# Generated by Django 5.1.3 on 2025-01-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='formacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='idiomas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
