# Generated by Django 5.1.3 on 2025-01-07 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0008_inscricao_usuario_alter_inscricao_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricao',
            options={'ordering': ['vaga', 'nome'], 'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterModelOptions(
            name='vaga',
            options={'ordering': ['-data_publicacao'], 'verbose_name': 'Vaga', 'verbose_name_plural': 'Vagas'},
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='mensagem',
            field=models.TextField(blank=True, default='Sem mensagem', null=True, verbose_name='Mensagem do candidato'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experiencia_profissional',
            field=models.TextField(blank=True, default='Não informado', null=True, verbose_name='Experiência Profissional'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='formacao_academica',
            field=models.TextField(blank=True, default='Não informado', null=True, verbose_name='Formação Acadêmica'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo_usuario',
            field=models.CharField(choices=[('Candidato', 'Candidato'), ('Empresa', 'Empresa')], default='Candidato', max_length=50, verbose_name='Tipo de usuário'),
        ),
    ]
