# Generated by Django 5.1.3 on 2025-01-07 18:21

import vagas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0009_alter_inscricao_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[vagas.models.validar_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[vagas.models.validar_cpf], verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_cobranca',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Cobrança'),
        ),
        migrations.AddField(
            model_name='profile',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='profile',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='profile',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='profile',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experiencia_profissional',
            field=models.TextField(blank=True, null=True, verbose_name='Experiência Profissional'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='formacao_academica',
            field=models.TextField(blank=True, null=True, verbose_name='Formação Acadêmica'),
        ),
    ]
